openapi: 3.1.0
info:
  title: Loan Evaluation API
  description: >
    API for evaluating loan eligibility based on risk profiles, borrower checks, and SME risk rules.
  version: "1.0.0"
servers:
  - url: https://loan-decision-api.onrender.com
components:
  securitySchemes:
    apiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
  schemas:
    BorrowerTypeResponse:
      type: object
      properties:
        decision:
          type: string
          enum: ["PASS", "FAIL"]
        explanation:
          type: string
        confidence:
          type: number
      required:
        - decision
        - explanation
        - confidence
    BorrowerIDResponse:
      type: object
      properties:
        decision:
          type: string
          enum: ["PASS", "CONDITIONAL_PASS", "FAIL"]
        explanation:
          type: string
        confidence:
          type: number
      required:
        - decision
        - explanation
        - confidence
    OpenBankingResponse:
      type: object
      properties:
        decision:
          type: string
          enum: ["PASS", "CONDITIONAL_PASS", "FAIL"]
        explanation:
          type: string
        confidence:
          type: number
      required:
        - decision
        - explanation
        - confidence
    SMERiskResponse:
      type: object
      properties:
        decision:
          type: string
          enum: ["PASS", "FLAG/AI", "FLAG/UW", "FAIL", "CONDITIONAL_PASS"]
        explanation:
          type: string
        confidence:
          type: number
      required:
        - decision
        - explanation
        - confidence
    UnderwriterSchema:
      type: object
      properties:
        version:
          type: string
        instructions:
          type: object
          properties:
            role:
              type: string
            objective:
              type: string
            prompt_guidelines:
              type: array
              items:
                type: string
            output_structure:
              type: object
              additionalProperties:
                type: string
          required:
            - role
            - objective
            - prompt_guidelines
            - output_structure
        data_sources:
          type: object
          additionalProperties:
            type: string
        fallback:
          type: string
        audit_and_versioning:
          type: object
          properties:
            rule_version:
              type: string
            timestamp:
              type: string
            audit_trail:
              type: string
          required:
            - rule_version
            - timestamp
            - audit_trail
        compliance_notes:
          type: string
      required:
        - version
        - instructions
        - data_sources
        - fallback
        - audit_and_versioning
        - compliance_notes
    ProductionFallback:
      type: object
      properties:
        function_name:
          type: string
        domain:
          type: string
        message:
          type: string
        action_id:
          type: string
      required:
        - function_name
        - domain
        - message
        - action_id
    EvaluationDecision:
      type: object
      properties:
        decision:
          type: string
          description: The decision outcome (e.g., PASS, FLAG/AI, etc.).
        confidence:
          type: number
          description: The confidence level of the decision.
        explanation:
          type: string
          description: The explanation for the decision.
      required:
        - decision
        - confidence
        - explanation
    NarrativeCheckRequest:
      type: object
      properties:
        evaluation:
          $ref: '#/components/schemas/EvaluationDecision'
        narrative:
          type: string
          description: The narrative explanation to check.
      required:
        - evaluation
        - narrative
paths:
  /evaluate/borrower-type:
    post:
      operationId: evaluateBorrowerType
      summary: Evaluate borrower type.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                borrower_type:
                  type: string
                  description: Borrower type (e.g., LTD, Sole Trader, LLP).
              required:
                - borrower_type
      responses:
        "200":
          description: Borrower type evaluation response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BorrowerTypeResponse'
  /evaluate/borrower-id:
    post:
      operationId: evaluateBorrowerID
      summary: Evaluate borrower ID verification.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                is_verified:
                  type: boolean
                  description: True if the borrower's ID is verified.
              required:
                - is_verified
      responses:
        "200":
          description: Borrower ID verification response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BorrowerIDResponse'
  /evaluate/open-banking:
    post:
      operationId: evaluateOpenBanking
      summary: Evaluate open banking connectivity.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                is_connected:
                  type: boolean
                  description: True if open banking is connected.
              required:
                - is_connected
      responses:
        "200":
          description: Open banking evaluation response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenBankingResponse'
  /evaluate/sme-risk:
    post:
      operationId: evaluateSMERisk
      summary: Evaluate SME risk and loan eligibility.
      description: >
        This endpoint evaluates SME risk based on provided profile, risk profile, stressed DSCR,
        loan amount, loan type, industry sector, and provided documents.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                smeProfile:
                  type: string
                  enum: ["EB", "ESB", "NTB", "SU"]
                  description: SME profile.
                riskProfile:
                  type: string
                  enum: ["T1", "T2", "T3"]
                  description: Risk profile.
                stressedDSCR:
                  type: number
                  description: Stressed DSCR value.
                loanAmount:
                  type: number
                  description: Requested loan amount.
                loanType:
                  type: string
                  enum: ["secured", "unsecured"]
                  description: Type of loan.
                industrySector:
                  type: string
                  description: Industry sector.
                  default: "Wholesale and Retail Trade"
                providedDocs:
                  type: array
                  items:
                    type: string
                  description: List of provided documents.
                  default: []
              required:
                - smeProfile
                - riskProfile
                - stressedDSCR
                - loanAmount
                - loanType
      responses:
        "200":
          description: SME risk evaluation response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SMERiskResponse'
  /underwriter-schema:
    get:
      operationId: getUnderwriterSchema
      summary: Retrieve the underwriter schema.
      description: >
        In staging mode, returns the full underwriter schema.
        In production mode, returns a fallback response requiring approval.
      responses:
        "200":
          description: Underwriter schema or production fallback response.
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/UnderwriterSchema'
                  - $ref: '#/components/schemas/ProductionFallback'
  /generate-narrative:
    post:
      operationId: generateNarrative
      summary: Generate narrative explanation for an evaluation decision.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EvaluationDecision'
      responses:
        "200":
          description: Narrative explanation generated by GPT.
          content:
            application/json:
              schema:
                type: object
                properties:
                  narrative:
                    type: string
                    description: The generated narrative explanation.
  /generate-and-verify-narrative:
    post:
      operationId: generateAndVerifyNarrative
      summary: Generate and verify narrative explanation for an evaluation decision.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EvaluationDecision'
      responses:
        "200":
          description: Narrative explanation that has been generated and verified.
          content:
            application/json:
              schema:
                type: object
                properties:
                  narrative:
                    type: string
                    description: The generated and verified narrative explanation.
  /check-narrative:
    post:
      operationId: checkNarrative
      summary: Check narrative consistency against evaluation decision.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NarrativeCheckRequest'
      responses:
        "200":
          description: Result of narrative consistency check.
          content:
            application/json:
              schema:
                type: object
                properties:
                  check_result:
                    type: string
                    description: The result of the narrative consistency check.
