openapi: 3.1.0
info:
  title: Loan Decision API
  description: API that evaluates SME loan applications based on risk profiles.
  version: 1.0.0
servers:
  - url: https://loan-decision-api.onrender.com  # Replace with your actual Render API URL
paths:
  /evaluate/sme-risk:
    post:
      operationId: evaluateSMERisk
      summary: Evaluate a loan application based on SME risk.
      description: This endpoint analyzes the SME profile, risk tier, and financial data to determine loan eligibility.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                smeProfile:
                  type: string
                  enum: [EB, ESB, NTB, SU]
                riskProfile:
                  type: string
                  enum: [T1, T2, T3]
                stressedDSCR:
                  type: number
                loanAmount:
                  type: number
                loanType:
                  type: string
                  enum: [secured, unsecured]
      responses:
        "200":
          description: Loan decision response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  decision:
                    type: string
                    enum: [PASS, FLAG/AI, FLAG/UW, FAIL]
                  explanation:
                    type: string
